# Generated by Django 3.2.2 on 2021-11-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduslogg', '0003_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, null=True)),
                ('snap', models.ImageField(null=True, upload_to='')),
                ('content', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
