# Generated by Django 3.2.2 on 2021-11-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduslogg', '0005_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
