# Generated by Django 3.2.2 on 2021-11-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduslogg', '0009_course_coursecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careeroption',
            name='category',
        ),
        migrations.AddField(
            model_name='careercategory',
            name='careers',
            field=models.ManyToManyField(null=True, related_name='careers', to='eduslogg.CareerOption'),
        ),
    ]
