# Generated by Django 3.2.2 on 2021-11-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduslogg', '0010_auto_20211115_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careercategory',
            name='careers',
            field=models.ManyToManyField(null=True, related_name='streams', to='eduslogg.CareerOption'),
        ),
    ]
