# Generated by Django 3.2.2 on 2021-11-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduslogg', '0011_alter_careercategory_careers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_category',
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='courses',
            field=models.ManyToManyField(null=True, related_name='streams', to='eduslogg.Course'),
        ),
    ]
