# Generated by Django 3.2.2 on 2021-11-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduslogg', '0012_auto_20211115_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careercategory',
            name='careers',
            field=models.ManyToManyField(related_name='streams', to='eduslogg.CareerOption'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='courses',
            field=models.ManyToManyField(related_name='streams', to='eduslogg.Course'),
        ),
    ]
